### ISSUE TITLE
Selection cleared after "play"

### ISSUE THREAD

**Issue by foreachthing** [Premo36/DML2.X#2]
Current behavior: 
1. select your mods
1. click "play"
1. change your mind about one mod and close this window
1. selection is cleared! :-\

Expected behavior: 
1. select your mods
1. click "play"
1. change your mind about one mod and close this window
1. selection is unchanged

**Comment by Premo36** [comment]
Fixed. Can be tested right now with the v2.3 Beta 1 
https://github.com/Premo36/DML2.X/releases/tag/v2.3-beta%231

**Comment by foreachthing** [comment]
Thanks!!! 
Somehow github did not notify me ... ?!?

**Comment by Premo36** [comment]
No problem :)
(BTW That beta is old now, you can find the stable 2.3 here on github https://github.com/Premo36/DML2.X/releases/tag/v2.3 or on ModDB  https://www.moddb.com/mods/doom-mod-loader/downloads)

**Comment by foreachthing** [comment]
Yeah, that's why I found out about it! 2.2 asked me to update ;-)
