### ISSUE TITLE
Crash on Mac

### ISSUE THREAD

**Issue by CandiceJoy** [Premo36/DML2.X#27]
[console-err.log](https://github.com/Premo36/DML2.X/files/8688909/console-err.log)
[console.log](https://github.com/Premo36/DML2.X/files/8688910/console.log)
[mono_crash.92acaffcd.4.json.log](https://github.com/Premo36/DML2.X/files/8688927/mono_crash.92acaffcd.4.json.log)

Run from terminal (ZSH) using the command 'mono DML\ v2.5\ \[Mono\].exe >console.log 2>console-err.log'.  14" M1 Pro Mac, 16gb RAM, 1tb HDD.  Stable and Visual Studio channels do the same thing.  Note that I did have mono installed before DML, but I installed mono from the website in the instructions before attempting to run it.

**Comment by Premo36** [comment]
Thanks for the report. As I said in download page DML 2.X on Mac it's untested, as I don't own a mac. I read the attached logs but sadly there was nothing that particullary stood out to me. Also if recall correctly mono does not have a native application for M1 Macs, so it's running trough rossetta which add another layer to everything. I'm sorry but right now I can't  fix this.
